name: Test Action

on:
  pull_request:
    paths:
      - 'input/**'

jobs:
  update_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: ls -l input/* | wc -l > output/nFiles.txt
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.head_ref }}
          author: "Automated Action"
          path: "output/"
          commit-message: "build: output"
